### ISSUE TITLE
IndexOutOfBoundsException Scheduling a room

### ISSUE THREAD

**Issue by elliottpicker** [gin-nader/MSCS721-roomScheduler#1]
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(Unknown Source)
	at java.util.ArrayList.get(Unknown Source)
	at com.marist.mscs721.RoomScheduler.scheduleRoom(RoomScheduler.java:277)
	at com.marist.mscs721.RoomScheduler.main(RoomScheduler.java:57)

Exception thrown while trying to use   _**3 - Schedule a room**_ 
This was done on windows 10 java version "1.8.0_121"  git commit afS5352 Feb 24, 2017 
	Steps to recreate
option 1 – Add a room
option 3 – schedule a room
enter start and end time as usual
IndexOutOfBoundsException thrown
	This is a defect as the schedule a room function is broken.

**Comment by gin-nader** [comment]
Fixed
