### ISSUE TITLE
ArrayIndexOutOfBoundsException Removing a room

### ISSUE THREAD

**Issue by elliottpicker** [gin-nader/MSCS721-roomScheduler#2]
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(Unknown Source)
	at java.util.ArrayList.remove(Unknown Source)
	at com.marist.mscs721.RoomScheduler.removeRoom(RoomScheduler.java:190)
	at com.marist.mscs721.RoomScheduler.main(RoomScheduler.java:54)

Exception thrown while trying to use _**2 - Remove a room**_
This was done on windows 10 java version "1.8.0_121" git commit afS5352 Feb 24, 2017
Steps to recreate
option 1 – Add a room
option 2 - Remove a room

ArrayIndexOutOfBoundsException thrown
This is a defect as the remove a room function is broken.

**Comment by gin-nader** [comment]
Fixed
